export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const SAVE_DATA = 'SAVE_DATA';

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

export const NEXT_QUESTION = 'NEXT_QUESTION';

export const UPDATE_SECOND = 'UPDATE_SECOND';

export const START_CRONOMETER = 'START_CRONOMETER';

export const STOP_CRONOMETER = 'STOP_CRONOMETER';

export const BTN_NEXT = 'BTN_NEXT';

export const REVEAL_ANSWERS = 'REVEAL_ANSWERS';

export const SET_CHRONOMETER = 'SET_CHRONOMETER';

export const SET_SCORE = 'SET_SCORE';

export const SET_ASSERTION = 'SET_ASSERTION';

export const RESET_STATE_LOGIN = 'RESET_STATE_LOGIN';
export const RESET_STATE_PLAYER = 'RESET_STATE_PLAYER';
export const RESET_STATE_QUESTIONS = 'RESET_STATE_QUESTIONS';
