export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const SAVE_DATA = 'SAVE_DATA';

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

export const NEXT_QUESTION = 'NEXT_QUESTION';

export const UPDATE_SECOND = 'UPDATE_SECOND';

export const START_CRONOMETER = 'START_CRONOMETER';

export const STOP_CRONOMETER = 'STOP_CRONOMETER';

export const BTN_NEXT = 'BTN_NEXT';
